language: python
os:
  - linux
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "nightly"
cache:
  directories:
    - $HOME/.cache/pip
before_install:
  - python --version
  - uname -a
  - lsb_release -a
install:
  - pip install pipenv
  - pipenv install --dev --three
  - pip install .
script:
  - pytest --cov=twintrimmer --cov-fail-under=100
  - behave
  - sphinx-build -n -b html -d docs/_build/doctrees docs/ docs/_build/html
