language: python
python:
  - "3.4"
  - "3.5"
  - "nightly"
cache:
  directories:
    - $HOME/.cache/pip
install:
  - pip install .
  - pip install nose
  - pip install git+https://github.com/jmcgeheeiv/pyfakefs
  - pip install -r requirements-test.txt
script:
  - python -m nose
  - behave
