language: python
python:
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "nightly"
  # does not have headers provided, please ask https://launchpad.net/~pypy/+archive/ppa
  # maintainers to fix their pypy-dev package.
  - "pypy3"
# command to install dependencies
install:
  - pip install .
  - pip install git+https://github.com/jmcgeheeiv/pyfakefs
# command to run tests
script: python -m nose
