language: python
os:
  - linux
python:
  - "3.4"
  - "3.5"
  - "3.5-dev"
  - "nightly"
cache:
  directories:
    - $HOME/.cache/pip
before_install:
  - python --version
  - uname -a
  - lsb_release -a
install:
  - pip install .
  - pip install -r requirements-dev.txt
  - pip freeze
script:
  - python -m nose --with-coverage --cover-package twintrimmer --cover-min-percentage=99 --cover-erase
  - behave
  - sphinx-build -n -b html -d docs/_build/doctrees docs/ docs/_build/html
